### ISSUE TITLE
Add smooth scrolling background - SuperSpeechSaga/app.py

### ISSUE THREAD

**Issue by ruhi47** [TusharAMD/SuperSpeechSaga#32]
Hey @TusharAMD ,

I would like to add some smooth transitions to background when character moves and some minor changes.
I am GSSOC'24 Contributor, please assign me this issue.

**Comment by TusharAMD** [comment]
Hi @ruhi47 its great that you are interested in adding scrolling window to the current game, but it would be nice if you could also focus on new games from scratch. Because the game right now in the repository is just a prototype. I think making new game would be more interesting and you would get more to learn. Check the issues, if you have some other game in your mind then make a issue and start working on it.

**Comment by ruhi47** [comment]
I will surely look into it, thanks @TusharAMD 😄

**Comment by SuhaniStark** [comment]
Could you please assign this issue to me under GSSOC'24.

**Comment by AashishKumar-3002** [comment]
Hi @TusharAMD can you assign me this issue

**Comment by Ar7109** [comment]
Hi @TusharAMD can you please assign me this issue
